# @package _global_
defaults:
  - /base
  - /task: country_borders
  - /model: gemma3_12b_it
  - /analysis/subspace
  - _self_
task:
  enumerate_all: true # training on all possible examples, test = train
  target_variable: country

subspace:
  method: pca
  layers: [28]
  k_features: 32
  token_positions: [last_token]
  visualization:
    figure_format: png
