"""Session-local method `centroid_graph_geodesic`.

Generated by `/setup-methods`. See set_up_method.md alongside this file for the
spec; see ARCHITECTURE.md §3 for the layering rules this module respects.
"""

from .centroid_graph_geodesic import centroid_graph_geodesic

__all__ = ["centroid_graph_geodesic"]
